house/urls.py
from django.conf.urls import patterns, include, url
from house.views import StoryList, StoryView, UserStoryView, HomePage
from house.account import *
from house.models import *
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',

    # Homepage
    url(r'^$', HomePage.as_view(), name='home'),

    # General Stories
    url(r'^stories/$', StoryList.as_view(), name='story_list'),

    # url(r'category/(?P<name>[-a-z0-9_]+)/$', CategoryView.as_view(), name='category_view'),

	# url(r'feeds/latest/$', LatestEntriesFeed()),

    # Account Info
    url(r'^account/settings/$', login_required(AuthorUpdate.as_view()), name='author_update'),
    url(r'^account/dashboard/$', login_required(AccountDashboard.as_view()), name='dashboard'),

    # Account StoriesManagement
    url(r'^account/stories/$', login_required(AccountStories.as_view()), name='admin_story_list'),
    url(r'^account/stories/write/$', login_required(StoryCreate.as_view()), name='story_add'),
    url(r'^account/stories/(?P<pk>\d+)/edit/$', login_required(StoryUpdate.as_view()), name='story_edit'),
    url(r'^account/stories/(?P<pk>\d+)/delete/$', login_required(StoryDelete.as_view()), name='story_delete'),

    # General User Matching
    url(r'^(?P<user>[-a-z0-9_]+)/(?P<slug>[-a-z0-9_]+)/$', StoryView.as_view(), name="story_view"),
    url(r'^(?P<pk>[-a-z0-9_]+)/$', UserStoryView.as_view(), name="user_view"),

)

storieshouse/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
# ... the rest of your URLconf goes here ...
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'storieshouse.views.home', name='home'),

    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'auth/login.html'}),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/?logged_out=true'}),
    url(r'^change_password/$', 'django.contrib.auth.views.password_change', {'post_change_redirect': '/account/'}),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # Podcast URLs
    url(r'^podcast/', include('podcast.urls')),

    # Story URLs
    url(r'^', include('house.urls')),
)

urlpatterns += staticfiles_urlpatterns()

house/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe
from django.template.defaultfilters import slugify
from django.db.models import Count
from datetime import datetime, timedelta

class Collection(models.Model):
	name = models.CharField(max_length = 255)
	stories = models.ManyToManyField('Story', through='CollectionMembership')

	image = models.URLField()

	def __unicode__(self):
		return self.name

class CollectionMembership(models.Model):
	story = models.ForeignKey('Story')
	collection = models.ForeignKey(Collection)
	collection_order = models.IntegerField()

class Category(models.Model):
	name = models.CharField(max_length = 15)
	html_class = models.CharField(max_length = 15)
	description = models.TextField()

	def __unicode__(self):
		return self.name

class StoryAuthor(models.Model):
	user = models.ForeignKey(User)
	about = models.TextField()

	avatar = models.URLField()

	def __unicode__(self):
		return "StoryAuthor: %s" % self.user.username

	@staticmethod
	def find(u):
		author, created = StoryAuthor.objects.get_or_create(user=u)
		return author

	@staticmethod
	def top(limit, early_date):
		h = Hit.objects.filter(date__gt=early_date).values('author').annotate(the_count=Count('author')).order_by('-the_count')[:limit]
		return map(lambda x: User.objects.get(id=x["author"]), h)

# Create your models here.
class Story(models.Model):
	ICON_CHOICES = (
		("bolt", "Lightning Bolt"),
		("road", "Road"),
		("beaker", "Beaker"),
		("globe", "Globe"),
		("cut", "Scissors"),
		("credit-card", "Credit Card"),
		("bell", "Bell"),
		("bullhorn", "Bullhorn"),
		("comment", "Comment"),
		("envelope", "Envelope"),
		("briefcase", "Briefcase"),
		("dashboard", "Dashboard"),
		("cloud", "Cloud"),
		("film", "Film"),
		("headphones", "Headphones"),
		("calendar", "Calendar"),
		("coffee", "Coffee"),
		("leaf", "Leaf"),
		("refresh", "Refresh"),
		("glass", "Martini"),
		("camera-retro", "Camera"),
		("laptop", "Laptop")
	)

	title = models.TextField()
	body = models.TextField()
	icon = models.CharField(max_length = 30, choices = ICON_CHOICES, blank = True, null = True)
	image = models.URLField(blank = True, null = True)
	user = models.ForeignKey(User)
	category = models.ForeignKey(Category)
	published = models.BooleanField()
	slug = models.SlugField()
	viewcount = models.IntegerField()
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta:
		ordering = ['-date_added']

	def save(self, *args, **kwargs):
		self.slug = slugify(self.title)
		super(Story, self).save(*args, **kwargs)

	def get_absolute_url(self):
		return ("/" + self.user.username + "/" + self.slug)

	def hits(self):
		return self.hit_set.count() + self.viewcount

	def hits_this_week(self):
		lastweek = datetime.now() - timedelta(weeks=1)
		return Hit.objects.filter(date__gt=lastweek, story=self).count()

	def register_hit(self):
		h = Hit()
		h.story_id = self.id
		h.author_id = self.user.id
		h.save()
		return

	def __unicode__(self):
		return '%s by %s' % (self.title, self.user)

	@staticmethod
	def top_by_author(limit, author, early_date):
		h = Hit.objects.filter(date__gt=early_date, author=author).values('story').annotate(the_count=Count('story')).order_by('-the_count')[:limit]
		return map(lambda x: Story.objects.get(id=x["story"]), h)

	@staticmethod
	def top(limit, early_date):
		h = Hit.objects.filter(date__gt=early_date).values('story').annotate(the_count=Count('story')).order_by('-the_count')[:limit]
		return map(lambda x: Story.objects.get(id=x["story"]), h)

class Hit(models.Model):
	date = models.DateTimeField(auto_now_add=True)
	story = models.ForeignKey(Story)
	author = models.ForeignKey(User)

house/forms.py
from django import forms
from house.models import Story, StoryAuthor
from django.forms.widgets import *

class StoryForm(forms.ModelForm):
    class Meta:
        model = Story
        exclude = ('user', 'date_added', 'slug', 'viewcount')
        widgets = {
            'title': TextInput(attrs={'class': 'form-control'}),
            'body': Textarea(attrs={'class': 'form-control'}),
            'icon': Select(attrs = {'class': 'form-control'}),
            'image': TextInput(attrs = {'class': 'form-control', 'placeholder': 'Use icon for story.'}),
            'category': Select(attrs = {'class': 'form-control'}),
            # 'published': CheckboxInput(attrs = {'class': 'form-control'}),
        }

class StoryAuthorForm(forms.ModelForm):
    about = forms.CharField(widget = Textarea(attrs = {'class': 'form-control'}))
    avatar = forms.CharField(widget = TextInput(attrs = {'class': 'form-control'}))
    class Meta:
        model = StoryAuthor
        exclude = ('user')

storieshouse/templates/house_admin/dashboard.html
{% extends "house_admin/layout.html" %}

{% block title %} :: Dashboard {% endblock %}
{% block dash_active %}active{% endblock %}

{% block admin_title %}Dashboard{% endblock %}

{% block admin_content %}
<div class="actions">
	<a href="{% url story_add %}" class="btn btn-success btn-sm"><i class="fa fa-plus"></i> Create Story</a>
	<a href="#" class="btn btn-default btn-sm"><i class="fa fa-gears"></i> Account Settings</a>
	<a href="#" class="btn btn-danger btn-sm" onclick="alert('Haha. Not going to happen.');"><i class="fa fa-envelope"></i> Complain to Hunter</a>
</div>
<br/>
<div class="row">
	<div class="col-sm-4">
		<div class="panel panel-default">
			<div class="panel-heading text-center">
				Total Views
			</div>
			<div class="panel-body text-center stat">
				<span>{{ total_views }}</span>
			</div>
		</div>
		<div class="panel panel-default">
			<div class="panel-heading text-center">
				Total Stories
			</div>
			<div class="panel-body text-center stat">
				<span>{{ total_stories }}</span>
			</div>
		</div>
	</div>
	<div class="col-sm-8">
		<div class="panel panel-default">
			<div class="panel-heading text-center">
				This Week's Views
			</div>
			<div class="panel-body text-center graph">
				<div id="graph-views-axis" class="y-axis"></div>
				<div id="graph-views"></div>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-sm-8">
		<div class="panel panel-default">
			<div class="panel-heading text-center">
				Top Stories (by views this week)
			</div>
			<div class="panel-body stat">
				<ol>
					{% for x in top_stories %}
					<li><a href="{% url story_view x.user.username x.slug %}">{{ x.title }}</a> <span class="text-muted">({{ x.hits_this_week }} views)</span></li>
					{% endfor %}
				</ol>
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block admin_js %}


<script>
createGraph("#graph-views", 
	[ 
		{% for x in views %}
		{ x: -{{ forloop.counter0 }}, y: {{ x.count }} },
		{% endfor %}
	], [{x: -6, y:0},]);
</script> 
{% endblock %}

storieshouse/templates/house_admin/layout.html
{% extends "base.html" %}

{% load house_extras %}

{% block home_active %}{% endblock %}

{% block css_extras %}
		<link href="/static/css/admin.css" rel="stylesheet">
{% endblock %}

{% block js_extra %}
		<!-- JavaScript Graphing Library -->
		<script src="http://cdnjs.cloudflare.com/ajax/libs/d3/3.3.11/d3.min.js"></script>
		<script src="http://cdnjs.cloudflare.com/ajax/libs/rickshaw/1.3.0/rickshaw.min.js"></script>

		<!-- // <script src="/js/main.js"></script> -->

		<!-- Custom JavaScript for the Menu Toggle -->
		<script>
			$("#menu-toggle").click(function(e) {
			e.preventDefault();
			$("#wrapper").toggleClass("active");
			});
		</script>
	<script src="/static/js/admin.js"></script>
	{% block admin_js %}{% endblock %}
{% endblock %}

{% block navigation %}{% endblock %}

{% block content %}
		<div id="wrapper">

		<!-- Sidebar -->
			<div id="sidebar-wrapper">
				<ul class="sidebar-nav">
					<li class="sidebar-brand">
						<a href="/"><span class="accent"><i class="fa fa-home"></i> Stories</span>House</a>
					</li>
					<!-- End Other Auctions -->
					<li class="{% block dash_active %}{% endblock %}"><a href="{% url dashboard %}"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a></li>
					<li class="{% block articles_active %}{% endblock %}"><a href="{% url admin_story_list %}"><i class="fa fa-fw fa-list"></i> Stories</a></li>
					<li class="{% block podcasts_active %}{% endblock %}"><a href="/account/podcasts/"><i class="fa fa-fw fa-play-circle-o"></i> Podcasts</a></li>
					<!-- <li class="{% block analytics_active %}{% endblock %}"><a href="/account/analytics/"><i class="fa fa-fw fa-compass"></i> Analytics</a></li> -->
					<li class="{% block account_active %}{% endblock %}"><a href="{% url author_update %}"><i class="fa fa-fw fa-gears"></i> My Account</a></li>
					<li><a href="/"><i class="fa fa-fw fa-arrow-circle-o-left"></i> Back to StoriesHouse</a></li>
				</ul>
				<!-- <ul class="sidebar-nav fixed-bottom">
					<li><a href="#"><i class="fa fa-fw fa-user"></i> Hunter Leath <i class="fa fa-caret-down"></i></a></li>
				</ul> -->
			</div>

			<!-- Page content -->
			<div id="page-content-wrapper">
				<div class="content-header">
					<h3>
						<a id="menu-toggle" href="#" class="btn btn-primary btn-xs"><i class="fa fa-bars"></i> Menu</a>
						{% block admin_title %}{% endblock %}
					</h3>
				</div>
				<!-- Keep all page content within the page-content inset div! -->
				<div class="page-content inset">
					{% block admin_content %}{% endblock %}
				</div>
			</div>

		</div>
{% endblock %}

{% block footer %}{% endblock %}

storieshouse/templates/house_admin/story_form.html
{% extends 'house_admin/layout.html' %}

{% block title_bar %}: Write{% endblock %}
{% block articles_active %}active{% endblock %}

{% block admin_title %}{% if create %}New Story{% else %}{{ story.title }}{% endif %}{% endblock %}

{% block admin_js %}
<script src="/static/js/epiceditor.min.js"></script>
<script src="/static/js/editor.js"></script>
{% endblock %}

{% block admin_content %}
<style>
	textarea#id_body { display: none; }
	#epiceditor { height: 500px; }
</style>

<form action="{{ request.path }}" method="POST" role="form">
	{% csrf_token %}
	<div class="form-group">
		{{ form.title.errors }}
		<label for="id_title">Title:</label>
		{{ form.title }}
	</div>
	<div class="form-group">
		{{ form.body.errors }}
		<label for="id_body">Body:</label>
		<div id="epiceditor"></div>
		{{ form.body }}
		<p class="help-block">The body of your story can include <a href="http://daringfireball.net/projects/markdown/basics">Markdown</a> syntax.</p>
	</div>
	<div class="row">
		<div class="col-md-6">
			<div class="form-group">
				{{ form.icon.errors }}
				<label for="id_icon">Icon:</label>
				{% autoescape off %}
				{{ form.icon }}
				{% endautoescape %}
				<p class="help-block">The icon that appears next to your story's name. Using no icon will attempt to utilize the cover image, or will display the <a href="https://s3.amazonaws.com/storiestime/sh-default.png">default StoriesHouse image</a>.</p>
			</div>
		</div>
		<div class="col-md-6">
			<div class="form-group">
				{{ form.image.errors }}
				<label for="id_image">Cover Photo URL:</label>
				<div class="input-group">
					{{ form.image }}
					<span class="input-group-btn">
						<button class="btn btn-primary">Browse...</button>
					</span>
				</div>
				<p class="help-block">An image that appears at the top of your post. Optimal size: 1280x960.</p>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			<div class="form-group">
				{{ form.category.errors }}
				<label for="id_category">Category:</label>
				{{ form.category }}
			</div>
			<div class="checkbox">
				{{ form.published.errors }}
				<label>
					{{ form.published }} Published
				</label>
			</div>
		</div>
		<div class="col-md-6">
			<div class="panel">
				<div class="panel-body text-center i-preview">
					<p class="text-muted text-small"><span>Icon</span> or <span>Image</span> Preview</p>
					<img width="50%" style="margin-left: 25%;" src="https://s3.amazonaws.com/storiestime/sh-default.png" class="img-responsive"/>
					<i class="fa fa-4x"></i>
				</div>
			</div>
		</div>
	</div>
	<hr/>
	<div class="form-actions">
		<input type="submit" value="Save" class="btn btn-primary btn-sm"/>
		{% if not create %}
		<div class="pull-right">
			<a href="{% url story_delete story.id %}" class="btn btn-danger btn-sm">Delete Story</a>
		</div>
		{% endif %}
	</div>
</form>
<br/>
{% endblock %}

storieshouse/templates/house_admin/story_list.html
{% extends "house_admin/layout.html" %}

{% block title %} :: Stories {% endblock %}
{% block articles_active %}active{% endblock %}

{% block admin_title %}Stories List{% endblock %}

{% block admin_content %}
<div class="actions">
	<a href="{% url story_add %}" class="btn btn-success btn-sm"><i class="fa fa-plus"></i> Create Story</a>
</div>
<br/>
<table class="table table-bordered table-hover table-striped">
	<thead>
	<tr>
		<th>Title</th>
		<th class="hidden-xs">Posted</th>
		<th>Published</th>
		<th>Views</th>
	</tr>
	</thead>
	<tbody>
	{% for x in stories %}
	<tr>
		<td><a href="{% url story_edit x.id %}">{{ x.title }}</a></td>
		<td class="hidden-xs">{{ x.date_added }}</td>
		<td>{% if x.published %}<i class="fa fa-check"></i>{% endif %}</td>
		<td>{{ x.hits }}</td>
	</tr>
	{% endfor %}
	</tbody>
</table>
{% endblock %}

storieshouse/templates/house_admin/storyauthor_form.html
{% extends 'house_admin/layout.html' %}

{% block title_bar %}: Account{% endblock %}
{% block account_active %}active{% endblock %}

{% block admin_title %}
	{{ object.user.first_name }}'s <span class="muted">information</span>
{% endblock %}	

{% block admin_content %}
<br/>
<div class="row">
	<div class="col-md-6">
		<form action="{{ request.path }}" method="POST" role="form">
			{% csrf_token %}
			<div class="form-group">
				{{ form.about.errors }}
				<label for="id_about">About:</label>
				{{ form.about }}
			</div>
			<div class="form-group">
				{{ form.avatar.errors }}
				<label for="id_avatar">Avatar (Currently Unused):</label>
				{{ form.avatar }}
			</div>
			<input type="submit" value="Save" class="btn btn-primary btn-sm"/>
			<a href="/change_password/" class="btn btn-danger btn-sm">Change Password</a>
		</form>
	</div>
</div>
{% endblock %}